[package]
name = "kitx"
<<<<<<< HEAD
version = "0.0.3"
edition = "2021"
authors = ["Wu Jianqi <janchie@163.com>"]
=======
version = "0.0.2"
edition = "2021"
authors = ["Wu Jianqi <janchie@126.com>"]
>>>>>>> b0e16200fd5be220e3fbdfdf161f92205821e722
description = "基于sqlx的数据库操作轻封装，快速增删改查。"
repository = "https://github.com/wujianqi/kitx"
documentation = "https://docs.rs/kitx"
readme = "README.md"
keywords = ["sqlx", "CRUD", "database", "ORM"]
categories = ["database"]
license-file = "LICENSE"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
<<<<<<< HEAD
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "chrono", "json", "sqlite", "mysql"]}
tokio = { version = "1.42.0", features = ["full"]}
field_access = "0.1.11"
uuid = "1.12.0"
=======
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "chrono", "json", "sqlite"]}
tokio = { version = "1.42.0", features = ["full"]}
field_access = "0.1.11"
>>>>>>> b0e16200fd5be220e3fbdfdf161f92205821e722
